// Generated by CoffeeScript 1.7.1
var data, h, padding, s, s2, s3, s3data, w;

data = d3.range(5).map(function(n) {
  return (n + 1) * 5;
});

w = 500;

h = 100;

padding = 1;

s = function() {
  return d3.select('body').append('svg').attr('width', "" + w + "px").attr('height', "" + h + "px");
};

s().selectAll('circle').data(data).enter().append('circle').attr('cx', function(d, i) {
  return i * 50 + 25;
}).attr('cy', h / 2).attr('r', function(d) {
  return d;
}).attr('fill', 'yellow').attr('stroke', 'orange').attr('stroke-width', function(d) {
  return d / 2;
});

s2 = s();

s2.selectAll('rect').data(data).enter().append('rect').attr('fill', 'teal').attr('x', function(d, i) {
  return i * (w / data.length) + 20 * i;
}).attr('y', function(d) {
  return h - d * 3;
}).attr('width', w / data.length - padding).attr('height', function(d) {
  return d * 3;
}).attr('stroke', 'purple').attr('stroke-width', function(d) {
  return 10;
});

s2.selectAll('text').data(data).enter().append('text').text(function(d) {
  return d;
}).attr('x', function(d, i) {
  return i * (w / data.length) + (w / data.length) / 2 + 20 * i;
}).attr('y', function(d) {
  return h - d;
}).attr('text-anchor', 'middle').attr('fill', 'white');

s3data = [[5, 20], [480, 90], [250, 50], [100, 33], [330, 95], [410, 12], [475, 44], [25, 67], [85, 21], [220, 88]];

s3 = s();

s3.selectAll('circle').data(s3data).enter().append('circle').attr('cx', function(d) {
  return d[0];
}).attr('cy', function(d) {
  return d[1];
}).attr('r', function(d) {
  return Math.log2(d[1]);
});

s3.selectAll('text').data(s3data).enter().append('text').text(function(d) {
  return d[0] + ',' + d[1];
}).attr('x', function(d) {
  return d[0];
}).attr('y', function(d) {
  return d[1];
}).attr('fill', 'green');
